version: '3'
services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  bullmq-ui:
    image: deadly0/bull-board
    ports:
      - "3001:3000"
    environment:
      - REDIS_URL=redis://redis:6379
